# Generated by Django 4.1.3 on 2023-01-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0003_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managerid', models.IntegerField()),
                ('managername', models.CharField(default='', max_length=45)),
                ('dob', models.DateField(default='')),
                ('gender', models.CharField(default='', max_length=6)),
                ('address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=45)),
                ('city', models.CharField(default='', max_length=45)),
                ('mobileno', models.CharField(default='', max_length=12)),
                ('emailid', models.CharField(default='', max_length=45)),
                ('photograph', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
