# Generated by Django 4.1.3 on 2023-02-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0004_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=45)),
                ('lastname', models.CharField(default='', max_length=45)),
                ('dob', models.DateField(default='')),
                ('emailid', models.CharField(default='', max_length=45)),
                ('mobileno', models.CharField(default='', max_length=45)),
                ('alternateno', models.CharField(default='', max_length=45)),
                ('orgname', models.CharField(default='', max_length=45)),
                ('address', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=45)),
                ('city', models.CharField(default='', max_length=45)),
                ('photograph', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
