# Generated by Django 4.1.3 on 2023-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='employee',
            name='repassword',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AddField(
            model_name='manager',
            name='repassword',
            field=models.CharField(default='', max_length=45),
        ),
    ]
