# Generated by Django 4.1.3 on 2023-03-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='currentdate',
            field=models.DateTimeField(default='', max_length=15),
        ),
    ]
