# Generated by Django 4.1.3 on 2023-03-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0009_alter_feedback_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='currentdate',
            field=models.DateField(default=''),
        ),
    ]
