# Generated by Django 4.1.3 on 2023-03-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0010_alter_feedback_currentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='repassword',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='repassword',
        ),
    ]
