# Generated by Django 4.1.3 on 2023-03-02 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LeadGenerationApp', '0011_remove_employee_repassword_remove_manager_repassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='transactionid',
        ),
    ]
